name: VueJS Front end

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.18.1
    
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
        description: The built dist files

  deploy:
    runs-on: self-hosted
    needs: [ build ]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: dist
        path: dist
        description: The built dist files

    - name: Deploy (copy files for self-hosted nginx)
      run: |
        mkdir -p /var/www/gotwitch/html/
        cp -r dist/* /var/www/gotwitch/html/    
